In [22]:
# Import required modules.
from sklearn.impute import SimpleImputer
import numpy as np
import pandas as pd

In [29]:
# Create own data set.
data_set=np.array([[1,2,np.nan],[4,np.nan,6],[np.nan,8,9],[np.nan,11,np.nan]])
print('Original Data_set',data_set,sep='\n')

Original Data_set
[[ 1.  2. nan]
 [ 4. nan  6.]
 [nan  8.  9.]
 [nan 11. nan]]


In [30]:
# convert created dada set to pandas dataframe.
labels=['Feature_1','feature_2','feature_3']
df_original=pd.DataFrame(data_set,columns=labels)
df_original.head(5)

Feature_1  feature_2  feature_3
0        1.0        2.0        NaN
1        4.0        NaN        6.0
2        NaN        8.0        9.0
3        NaN       11.0        NaN

In [31]:
# Using SimpleImputer class.
imputer=SimpleImputer(strategy='median')
imputer.fit(df_original)

SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='median', verbose=0)

In [32]:
imputer.statistics_

array([2.5, 8. , 7.5])

In [33]:
# New data set.
data_set_new=imputer.transform(df_original)
print(data_set_new)

[[ 1.   2.   7.5]
 [ 4.   8.   6. ]
 [ 2.5  8.   9. ]
 [ 2.5 11.   7.5]]


In [34]:
# New pandas dataframe for new data set.
labels=['Feature_1','feature_2','feature_3']
df_new=pd.DataFrame(data_set_new,columns=labels)
df_new.head()

Feature_1  feature_2  feature_3
0        1.0        2.0        7.5
1        4.0        8.0        6.0
2        2.5        8.0        9.0
3        2.5       11.0        7.5